# Generated by Django 3.2.9 on 2021-11-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdataset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsetobject',
            name='nickname',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
