# Generated by Django 3.2.9 on 2021-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211117_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='added',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
